### ISSUE TITLE
TODO: We don't need the swerve anymore

### ISSUE THREAD

**Issue by DestructiveReasoning** [JRegimbal/ECSE-211#1]
Hey, sorry but I just realized that I forgot to remove the swerve functionality after I moved the sensor. We probably don't need it anymore. Also, I'm going to try to change the orientation of the sensor so that it's 'horizontal' rather than 'vertical'. That way it might detect stuff to its left and in front of it a little better.

**Comment by JRegimbal** [comment]
sounds good but why don't we need swerve anymore? unless you mean the swerving while straight in which case i actually think that's still important just because w our scale we could still run into the wall by just going straight.

either way i'm with you on changing the sensor orientation. i moved it a bit more inward on the robot just so it can see further ahead and to the left which helped a bit with avoiding obstacles.
